---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          # replace image for web depending on local or cloud kube
          image: ghcr.io/jasont2022/web:${{ github.sha }}
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_CONNSTRING
              value: mongodb://mongodb/blog

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - port: 8000
      targetPort: 8000