name: Blog
on: push

jobs:
  build:
    name: Build and publish docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.10.0
        with:
          # push: ${{ github.ref == 'refs/heads/master' }}
          push: true
          tags: ghcr.io/jasont2022/cis188-final/web:${{ github.sha }}
          context: web

  # deploy:
  #   name: Deploy latest version of code
  #   if: github.ref == 'refs/heads/master'
  #   needs: build

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     # TODO: deploy to AWS
  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1
      
  #     - name: Get a kubeconfig from AWS
  #       run: |
  #         aws eks --region us-east-1 update-kubeconfig --name cis188 --role-arn arn:aws:iam::474844133309:role/jastran --alias cis188
  #         kubectl config set-context --current --namespace=jastran
  #     - name: Deploy to Cluster
  #       run: |
  #         helm repo add cis188 https://helm.cis188.org
  #         helm upgrade --install --set fastapi.tag=${{ github.sha }} --set cronjob.tag=${{ github.sha }} -f installation-values.yaml aang cis188/bender-catalog
