# name: Blog
# on: push

# jobs:
#   test:
#     name: Test Application
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - run: |
#           pip install poetry
#           cd web
#           poetry install

#   build:
#     name: Build and Publish Docker Image
#     runs-on: ubuntu-latest
#     needs: test

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v1

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1

#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - name: Build and push Docker images
#         uses: docker/build-push-action@v2.10.0
#         with:
#           push: ${{ github.ref == 'refs/heads/master' }}
#           tags: ghcr.io/cis188/jastran/final-blog:${{ github.sha }}
#           context: web